[package]
name = "muxdeckd"
description = "The MuxDeck daemon."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "muxdeckd"
path = "src/main.rs"

[dependencies]
muxdeck-engine.workspace = true
