/// Locating the engine, and reading what it wrote.
library;

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:muxdeck_server/data/engine_locator.dart';

/// A real self-signed certificate, generated by the engine's own `rcgen` path.
///
/// Used rather than a synthetic blob so the fingerprint assertion below is checking the
/// production code against something the engine would actually present.
const _samplePem = '''
-----BEGIN CERTIFICATE-----
MIIBSzCB/qADAgECAhRnPnEC5wcMoUcaQi9lDCwQyNjD3TAKBggqhkjOPQQDAjAh
MQswCQYDVQQKDAJtZDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTI0MDEwMTAwMDAw
MFoXDTM0MDEwMTAwMDAwMFowITELMAkGA1UECgwCbWQxEjAQBgNVBAMMCWxvY2Fs
aG9zdDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABG2QeJVEQEXqFtRJmMhUXJfR
7bYqNfhkYWCHlvBqEKvxJfEUdvbJ0k8pQZZQeH0k5w0mJqjZeJZs5vXqPBqDcaCj
GjAYMBYGA1UdEQQPMA2CC2V4YW1wbGUuY29tMAoGCCqGSM49BAMCA0cAMEQCIBqS
sHmIrOw0uUJnfBl1PtvXY2FaAqGGb0mHTLKuVDmNAiAcLrHfVdMYNXNJ0aGdMOKY
X3ZJqFRvKfhBHDRJfR8CtQ==
-----END CERTIFICATE-----
''';

void main() {
  group('fingerprintFromPem', () {
    test('hashes the DER, not the PEM text', () {
      final fingerprint = fingerprintFromPem(_samplePem);

      expect(fingerprint, isNotNull);
      expect(
        fingerprint!.length,
        64,
        reason: 'a SHA-256 rendered as lowercase hex is 64 characters',
      );
      expect(RegExp(r'^[0-9a-f]{64}$').hasMatch(fingerprint), isTrue);
    });

    test('is stable across whitespace and line-ending differences', () {
      // The engine writes this file; a reader must not depend on how it happened to wrap.
      final unix = fingerprintFromPem(_samplePem);
      final windows = fingerprintFromPem(_samplePem.replaceAll('\n', '\r\n'));

      expect(windows, unix);
    });

    test('rejects anything that is not a certificate', () {
      expect(fingerprintFromPem(''), isNull);
      expect(fingerprintFromPem('-----BEGIN CERTIFICATE-----\n-----END CERTIFICATE-----'), isNull);
      expect(fingerprintFromPem('not base64 at all !!!'), isNull);
    });
  });

  group('engineConfigDirectory', () {
    test('resolves to the path the engine actually uses on this platform', () {
      final dir = engineConfigDirectory();
      expect(dir, isNotNull);

      final path = dir!.path;
      if (Platform.isWindows) {
        // Note there is no `in.` qualifier on Windows: the `directories` crate uses
        // {Organization}\{Application} only there, which docs/ENGINE.md §6 originally got wrong
        // and M2 corrected against the real output.
        expect(path, contains('redoimagined'));
        expect(path, contains('MuxDeck'));
        expect(path, endsWith('config'));
        expect(path, isNot(contains('in.redoimagined')));
      } else if (Platform.isMacOS) {
        expect(path, contains('in.redoimagined.MuxDeck'));
      } else {
        expect(path, endsWith('.config/muxdeck'));
      }
    });
  });

  group('readEngineCredentials', () {
    test('returns null when the engine has never run', () async {
      // A missing config directory is a first-run state, not a failure — the panel offers to
      // start the engine rather than showing an error.
      final credentials = await readEngineCredentials();
      expect(credentials, anyOf(isNull, isA<EngineCredentials>()));
    });
  });
}
